apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-dynamic-mysql-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
spec:
  clusterIP: None
  selector:
    app: mysql
    project: roboshop
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-headless
  replicas: 1

  selector:
    matchLabels:
      app: mysql
      project: roboshop

  template:
    metadata:
      labels:
        app: mysql
        project: roboshop
    spec:
      containers:
        - name: mysql
          image: 854481201869.dkr.ecr.us-east-1.amazonaws.com/stackly/mysql:1.0.0
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
            - configMapRef:
                name: mysql
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-ebs-dynamic
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql-ebs-dynamic
      spec:
        storageClassName: ebs-dynamic-mysql-sc
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
  labels:
    name: mysql
    project: roboshop
    environment: dev
    tier: db
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: roboshop
data:
  mysql-root-password: Roboshop@1
  