apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    name: mongodb
    project: roboshop
    environment: dev
    tier: db
spec:
  selector:
    name: mongodb
    project: roboshop
    environment: dev
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    name: mongodb
    project: roboshop
    environment: dev
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb
      project: roboshop
      environment: dev
      tier: db
  template:
    metadata:
      labels:
        name: mongodb
        project: roboshop
        environment: dev
        tier: db
    spec:
      containers:
      - name: mongodb
        image: kriiishmatic/mongodb:v1
        ports:
          - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10