apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop-eks-cluster
  region: us-east-1

managedNodeGroups:
  - name: roboshop-ng-dev

    instanceType: t3.small

    desiredCapacity: 1
    minSize: 1
    maxSize: 6

    privateNetworking: true

    subnets:
      - subnet-09e1785d7668c8762

    ssh:
      allow: true
      publicKeyName: k8s-practice-key

    securityGroups:
      attachIDs:
        - sg-010003368b1f4c38b




















# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: roboshop-eks-cluster
#   region: us-east-1

# managedNodeGroups:
#   - name: roboshop-ng-dev
#     instanceType: t3.small
#     desiredCapacity: 1
#     minSize: 1
#     maxSize: 5
#     spot: false

# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: roboshop-eks-cluster
#   region: us-east-1
#   version: "1.29"

# availabilityZones:
#   - us-east-1a
#   - us-east-1b

# vpc:
#   subnets:
#     public:
#       us-east-1a: {}
#       us-east-1b: {}

# managedNodeGroups:
#   - name: roboshop-nodegroup
#     instanceType: t3.medium
#     desiredCapacity: 2
#     minSize: 1
#     maxSize: 3

#     volumeSize: 20
#     amiFamily: AmazonLinux2

#     ssh:
#       allow: true

#     labels:
#       role: worker

#     tags:
#       nodegroup-role: worker