apiVersion : v1
kind : PersistentVolume
metadata:
  name : efs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0086cd2d15ca98b8d
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ""
  volumeName: efs-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-pod-static
spec:
  containers:
    - name: efs-container-static
      image: nginx:latest 
      volumeMounts:
        - name: efs-volume-static
          mountPath: /app/data/static/efs
  volumes:
    - name: efs-volume-static
      persistentVolumeClaim:
        claimName: efs-pvc